# Static self-check for Unity projects WITHOUT Unity.exe installed.
#
# Unlike run_check.ps1 (which drives `Unity.exe -batchmode`), this script needs
# NO Unity runtime. It reads .cs / .unity / .prefab as plain text and applies
# project-convention rules that a headless Unity build cannot catch, so it works
# on a machine where Unity is NOT installed at all (e.g. a code-only laptop).
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File Tools\static_check.ps1
#   powershell -ExecutionPolicy Bypass -File Tools\static_check.ps1 -Project "D:\Learn"
#
# Result file: %TEMP%\unity_static_audit.log  (ends with STATIC_AUDIT_RESULT: PASS/FAIL)
# Exit code:   0 = PASS, 1 = FAIL (there is at least one FAIL-level violation)
#
# NOTE: keep THIS FILE ASCII-only. PowerShell 5.1 decodes a BOM-less .ps1 with
# the ANSI codepage, so non-ASCII bytes in the source get garbled. Chinese text
# only appears inside the RESULT file (written as UTF-8), never in this source.

param(
    [string]$Project = ""
)

$ErrorActionPreference = 'Stop'

if (-not $Project) {
    $Project = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
}
$Project = $Project.TrimEnd('\', '/')

$ScriptsRoot = Join-Path $Project 'Assets\Scripts'
$AssetsRoot  = Join-Path $Project 'Assets'
$ResultLog   = Join-Path $env:TEMP 'unity_static_audit.log'

# ── counters / output buffer ─────────────────────────────────────────────
$script:PassCount = 0
$script:FailCount = 0
$script:SkipCount = 0
$script:Sb = New-Object System.Text.StringBuilder

function Add-Line([string]$Text)   { [void]$script:Sb.AppendLine($Text) }
function Add-Pass([string]$Name)   { $script:PassCount++; Add-Line "[PASS] $Name" }
function Add-Fail([string]$Name)   { $script:FailCount++; Add-Line "[FAIL] $Name" }
function Add-Skip([string]$Name)   { $script:SkipCount++; Add-Line "[SKIP] $Name" }
function Add-Info([string]$Text)   { Add-Line "[INFO] $Text" }

function Get-Rel([string]$Path) {
    if ($Path.StartsWith($Project, [System.StringComparison]::OrdinalIgnoreCase)) {
        return $Path.Substring($Project.Length).TrimStart('\', '/')
    }
    return $Path
}

function Read-Lines([string]$File) {
    return [System.IO.File]::ReadAllLines($File)
}

# Returns $true when a .cs file carries Unity's auto-generated marker
# ("// <auto-generated>", used by com.unity.inputsystem and other generators).
# Such files are machine-written (fields use the m_ prefix), so convention
# rules must NOT flag them as hand-written code violations.
function Test-IsAutoGenerated([string]$File) {
    $lines = Read-Lines $File
    $head = [Math]::Min(20, $lines.Count)
    for ($i = 0; $i -lt $head; $i++) {
        if ($lines[$i] -match '<auto-generated>') { return $true }
    }
    return $false
}

# Returns all .cs files under Assets\Scripts, optionally excluding the Editor
# folder (Editor-only code is allowed to use Debug.Log, etc.).
function Get-CsFiles([bool]$ExcludeEditor) {
    if (-not (Test-Path $ScriptsRoot)) { return @() }
    $all = @(Get-ChildItem $ScriptsRoot -Recurse -Filter *.cs -File)
    if (-not $ExcludeEditor) { return $all }
    return @($all | Where-Object { $_.FullName -notmatch '[\\/]Editor[\\/]' })
}

# ── FAIL-level checks ────────────────────────────────────────────────────

# Rule: game code (non-Editor) must NOT use Debug.Log (GC + console IO in
# runtime hot paths). LogError / LogWarning are allowed.
#
# Two kinds of Debug.Log are NOT violations (they are intentional debug output):
#   a. gated by an `if (...Debug...)` guard on the previous line (e.g. EventBus.DebugMode)
#   b. inside a debug/dump method (method name contains "ebug" / "Dump")
# Those are reported as INFO instead of FAIL, so they do not pollute the result.
function Test-DebugLogRule {
    $failHits = New-Object System.Collections.Generic.List[string]
    $okHits   = New-Object System.Collections.Generic.List[string]
    # method-signature pattern: name(...) at end of line, excluding keywords
    $sigPattern = '(?!(?:if|for|foreach|while|switch|catch|using|lock|return|new)\s*\()(\w+)\s*\([^;{}]*\)\s*\{?\s*$'

    foreach ($f in (Get-CsFiles $true)) {
        $lines = Read-Lines $f.FullName
        $prevLine = ''
        $inDebugMethod = $false
        $debugDepth = 0

        for ($i = 0; $i -lt $lines.Count; $i++) {
            $line = $lines[$i]
            $lineNo = $i + 1

            # (1) detect a debug/dump method signature while outside any method
            if (-not $inDebugMethod) {
                if ($line -match $sigPattern) {
                    $methodName = $Matches[1]
                    if ($methodName -match 'ebug|Dump') {
                        $inDebugMethod = $true
                        $debugDepth = 0
                    }
                }
            }

            # (2) track brace depth to know when the debug method ends
            if ($inDebugMethod) {
                $debugDepth += ([regex]::Matches($line, '\{')).Count
                $debugDepth -= ([regex]::Matches($line, '\}')).Count
                if ($debugDepth -le 0 -and $line -match '\}') {
                    $inDebugMethod = $false
                    $debugDepth = 0
                }
            }

            # (3) classify Debug.Log occurrences
            if ($line -match 'Debug\.Log\s*\(') {
                $protected = $false
                if ($inDebugMethod) { $protected = $true }
                elseif ($prevLine -match 'if\s*\([^)]*[Dd]ebug[^)]*\)\s*$') { $protected = $true }
                elseif ($line -match 'if\s*\([^)]*[Dd]ebug[^)]*\)') { $protected = $true }

                $loc = '  ' + (Get-Rel $f.FullName) + ':' + $lineNo
                if ($protected) { $okHits.Add($loc) } else { $failHits.Add($loc) }
            }

            $prevLine = $line
        }
    }

    if ($failHits.Count -eq 0) {
        Add-Pass 'Debug.Log banned in runtime scripts'
    } else {
        Add-Fail "Debug.Log banned in runtime scripts ($($failHits.Count) hit(s))"
        foreach ($h in $failHits) { Add-Line $h }
        Add-Info '  (Editor folder excluded; use LogError/LogWarning only in game code)'
    }
    if ($okHits.Count -gt 0) {
        Add-Info "Debug.Log gated by debug guard/method ($($okHits.Count) - acceptable)"
        foreach ($h in $okHits) { Add-Line $h }
    }
}

# Rule: every .cs / .inputactions must have a sibling .meta (Unity GUID is
# required to keep asset references intact).
function Test-MetaCompleteness {
    $missing = New-Object System.Collections.Generic.List[string]
    if (Test-Path $AssetsRoot) {
        Get-ChildItem $AssetsRoot -Recurse -File | Where-Object {
            $_.Extension -in @('.cs', '.inputactions')
        } | ForEach-Object {
            $meta = $_.FullName + '.meta'
            if (-not (Test-Path $meta)) { $missing.Add((Get-Rel $_.FullName)) }
        }
    }
    if ($missing.Count -eq 0) {
        Add-Pass 'Meta files present for .cs/.inputactions'
    } else {
        Add-Fail "Missing .meta files ($($missing.Count))"
        foreach ($m in $missing) { Add-Line "  $m" }
        Add-Info '  (let Unity generate the .meta, then commit it)'
    }
}

# Rule: no string-based type/method lookup (SendMessage / GetComponent("...")
# / GameObject.Find("...") / FindObjectOfType("...")). Use generic/typed APIs.
function Test-StringLookup {
    $pattern = 'SendMessage\s*\(|GetComponent\s*\(\s*"|GameObject\.Find\s*\(\s*"|FindObjectOfType\s*\(\s*"'
    $hits = New-Object System.Collections.Generic.List[string]
    foreach ($f in (Get-CsFiles $false)) {
        $lineNo = 0
        foreach ($line in (Read-Lines $f.FullName)) {
            $lineNo++
            if ($line -match $pattern) {
                $hits.Add("  " + (Get-Rel $f.FullName) + ":" + $lineNo + "  " + $line.Trim())
            }
        }
    }
    if ($hits.Count -eq 0) {
        Add-Pass 'No string-based type/method lookup'
    } else {
        Add-Fail "String-based type/method lookup found ($($hits.Count) hit(s))"
        foreach ($h in $hits) { Add-Line $h }
    }
}

# Scene / prefab text audit: detect missing-script references without Unity.
# A missing MonoBehaviour is serialized as m_Script: {fileID: 0}. This only
# runs when .unity/.prefab files exist in the repo (currently they do not).
function Test-SceneFiles {
    $sceneFiles = @()
    if (Test-Path $AssetsRoot) {
        $sceneFiles = @(Get-ChildItem $AssetsRoot -Recurse -File | Where-Object {
            $_.Extension -in @('.unity', '.prefab')
        })
    }
    if ($sceneFiles.Count -eq 0) {
        Add-Skip 'Scene/prefab text audit (no .unity/.prefab in repo)'
        return
    }

    $missing = New-Object System.Collections.Generic.List[string]
    foreach ($f in $sceneFiles) {
        $lineNo = 0
        foreach ($line in (Read-Lines $f.FullName)) {
            $lineNo++
            if ($line -match 'm_Script:\s*\{fileID:\s*0\s*\}') {
                $missing.Add("  " + (Get-Rel $f.FullName) + ":" + $lineNo)
            }
        }
    }
    if ($missing.Count -eq 0) {
        Add-Pass 'No missing-script references in scenes/prefabs'
    } else {
        Add-Fail "Missing-script references in scenes/prefabs ($($missing.Count))"
        foreach ($m in $missing) { Add-Line $m }
    }
}

# ── INFO-level checks (reported, do not fail the audit) ──────────────────

# Rule: a source line must stay within 120 chars. Reported only (auto-generated
# files / long URLs can trip it), so it does not fail the build.
function Test-LineWidth {
    $count = 0
    $max = 0
    foreach ($f in (Get-CsFiles $false)) {
        foreach ($line in (Read-Lines $f.FullName)) {
            if ($line.Length -gt 120) { $count++ }
            if ($line.Length -gt $max) { $max = $line.Length }
        }
    }
    if ($count -eq 0) {
        Add-Info "Line width OK (max $max chars, limit 120)"
    } else {
        Add-Info "Line width: $count line(s) over 120 chars (max $max) - review manually"
    }
}

# Rule (heuristic): private instance fields use the _ prefix. INFO only because
# regex field detection can false-positive on exotic declarations.
function Test-FieldNaming {
    $pattern = '^\s*private\s+(?!static\b|const\b|readonly\b)([\w<>,\[\]\.\s]+?)\s+([A-Za-z_]\w*)\s*[;=]'
    $hits = New-Object System.Collections.Generic.List[string]
    $skippedFiles = 0
    foreach ($f in (Get-CsFiles $false)) {
        # Unity-generated code (input actions, etc.) uses m_ prefix; skip it.
        if (Test-IsAutoGenerated $f.FullName) { $skippedFiles++; continue }
        $lineNo = 0
        foreach ($line in (Read-Lines $f.FullName)) {
            $lineNo++
            if ($line -match $pattern) {
                $field = $Matches[2]
                if ($field -notmatch '^_') {
                    $hits.Add("  " + (Get-Rel $f.FullName) + ":" + $lineNo + "  " + $line.Trim())
                }
            }
        }
    }
    if ($skippedFiles -gt 0) {
        Add-Info "Private field naming: skipped $skippedFiles auto-generated file(s)"
    }
    if ($hits.Count -eq 0) {
        Add-Info 'Private field naming OK (_ prefix convention)'
    } else {
        Add-Info "Private field naming: $($hits.Count) field(s) missing _ prefix (heuristic)"
        foreach ($h in $hits) { Add-Line $h }
    }
}

# ── main ─────────────────────────────────────────────────────────────────

Add-Line 'Static audit (no Unity.exe required)'
Add-Line "Project: $Project"
Add-Line ''

Test-DebugLogRule
Test-MetaCompleteness
Test-StringLookup
Test-SceneFiles
Test-LineWidth
Test-FieldNaming

Add-Line ''
Add-Line "TOTAL: pass=$($script:PassCount) fail=$($script:FailCount) skip=$($script:SkipCount)"
if ($script:FailCount -eq 0) {
    Add-Line 'STATIC_AUDIT_RESULT: PASS'
    $resultText = 'PASS'
} else {
    Add-Line 'STATIC_AUDIT_RESULT: FAIL'
    $resultText = 'FAIL'
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($ResultLog, $script:Sb.ToString(), $utf8NoBom)

Write-Host "Static audit: $resultText (pass=$($script:PassCount) fail=$($script:FailCount) skip=$($script:SkipCount))"
Write-Host "Result file: $ResultLog"

if ($script:FailCount -eq 0) { exit 0 } else { exit 1 }
